version: '3'
services:  
  security_server:
    build: Dockerfile-Security    
    ports:
     - "5005:5005"     
    environment:
     - ASPNETCORE_URLS=http://*:5005
     - ASPNETCORE_ENVIRONMENT=Production        