version: '3'
services:
  frontend_Portal:
    image: microsoft/dotnet:1.0-runtime
    command: bash -c "cd /app  && dotnet MyCompany.Frontend.Portal.dll" 
    volumes: 
        - ./MyCompany.Frontend.Portal/out:/app
    ports:
     - "5001:5001"
    environment:
     - ASPNETCORE_URLS=http://*:5001
     - ASPNETCORE_ENVIRONMENT=Production
  gateway_Portal:
    image: microsoft/dotnet:1.0-runtime 
    command: bash -c "cd /app  && dotnet MyCompany.Gateways.Portal.dll" 
    volumes: 
        - ./MyCompany.Gateways.Portal/out:/app
    ports:
     - "5002:5002"     
    environment:
     - ASPNETCORE_URLS=http://*:5002
     - ASPNETCORE_ENVIRONMENT=Production 