version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  teamcity_server_data: {}
  teamcity_server_logs: {}

services:
  postgres:
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: env.my
    restart: always

  teamcity-server:
    image: jetbrains/teamcity-server
    volumes:
      - teamcity_server_data:/data/teamcity_server/datadir
      - teamcity_server_logs:/opt/teamcity/logs
    ports:
      - 8111:8111
    depends_on:
      - postgres
    env_file: env.my
    restart: always

  teamcity-agent:
    privileged: true
    image: jetbrains/teamcity-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - teamcity_server_logs:/opt/teamcity/logs
    env_file: env.my
    restart: always
